#ifndef _AniPolkaVert_h_
#define _AniPolkaVert_h_


// Header generated from binary by WriteAsBinHeader()..
static const int AniPolkaVertLength = 218;
static const unsigned int AniPolkaVert[AniPolkaVertLength]={
    0x20205356,    0xFFFF0008,    0x00000048,    0x01020000,    0x00000012,    0x0000000F,    0x00000000,    0x00000000,    0x00000002,    0x00000004,
    0x00000004,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000048,    0x00000000,    0x00000000,    0x02020000,
    0x237821E4,    0x00000000,    0x00E40101,    0x02035500,    0x2EF821E4,    0x00000000,    0x00E40101,    0x0204AA00,    0x2EF821E4,    0x00000000,
    0x00E40101,    0x0205FF00,    0x0EF821E4,    0x00000000,    0x00000000,    0x02060000,    0x237822E4,    0x00000000,    0x00E40102,    0x02075500,
    0x2EF822E4,    0x00000000,    0x00E40102,    0x0208AA00,    0x2EF822E4,    0x00000000,    0x00E40102,    0x0209FF00,    0x0EF822E4,    0x00000000,
    0x0A000000,    0x00000002,    0x027820E4,    0x00000000,    0x01000000,    0x020B0000,    0x237823E4,    0x00000000,    0x01E40103,    0x020C5500,
    0x2EF823E4,    0x00000000,    0x01E40103,    0x020DAA00,    0x2EF823E4,    0x00000000,    0x01E40103,    0x020EFF00,    0x0EF823E4,    0x00000000,
    0x00000000,    0x01010000,    0x00F800E4,    0x00000000,    0x00000000,    0x01000000,    0x00F802E4,    0x00000000,    0x00000000,    0x01030000,
    0x00B803A4,    0x00000000,    0x00000000,    0x41020000,    0x00B801A4,    0x00000000,    0x00000000,    0x00000000,    0x1E000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x3F800000,    0x3F800000,    0x3F800000,    0x3F800000,    0x00000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,
    0x0000000C,    0x00000007,    0x00000009,    0x00000000,    0x00000004,    0x00000014,    0x00000009,    0x00000009,    0x00000000,    0x00000000,
    0x00000000,    0x0000000B,    0x00000009,    0x00010004,    0x00000000,    0x00000034,    0x00000005,    0x00000009,    0x00010004,    0x00000008,
    0x0000003A,    0x00000006,    0x00000006,    0x00010004,    0x0000000C,    0x00000041,    0x00000006,    0x00000006,    0x00010004,    0x00000004,
    0x0000001E,    0x00000004,    0x00000000,    0x00020001,    0x00000028,    0x00000023,    0x00000009,    0x0000000E,    0x00020001,    0x0000002C,
    0x0000002D,    0x00000003,    0x0000000E,    0x00020001,    0x00000008,    0x00000031,    0x00000002,    0x0000000E,    0x00020001,    0x00000018,
    0x505F6C67,    0x7469736F,    0x006E6F69,    0x726F4E69,    0x006C616D,    0x74726576,    0x6F507865,    0x69740073,    0x6E00656D,    0x616D726F,
    0x74614D6C,    0x70766D00,    0x00766D00,    0x6F50534D,    0x6F6E0073,    0x6C616D72,    0x65796500,    0x00636556,};

//checksum generated by simpleCheckSum()
static const unsigned int AniPolkaVertCheckSum = 228;

static const char* AniPolkaVertText = 
    "\n"
    "attribute vec4 iNormal;\n"
    "attribute vec4 vertexPos;\n"
    "attribute vec4 iColor;\n"
    "\n"
    "\n"
    "\n"
    "uniform float time;\n"
    "uniform vec4 lightPos;\n"
    "uniform mat4 normalMat;\n"
    "uniform mat4 mvp;\n"
    "uniform mat4 mv;\n"
    "\n"
    "varying vec4 MSPos;\n"
    "varying vec3 normal;\n"
    "varying vec3 eyeVec;\n"
    "\n"
    "const vec4 flatColor = vec4(1.0,0.0,0.0,0.0);\n"
    "\n"
    "void main()\n"
    "{\n"
    "        gl_Position = mvp*vertexPos;\n"
    "        eyeVec = - (mv*vertexPos).xyz;\n"
    "        MSPos = vertexPos + vec4(time);\n"
    "        \n"
    "        normal = (normalMat*iNormal).xyz;\n"
    "}";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader AniPolkaVertShader(AniPolkaVertText, AniPolkaVert, AniPolkaVertLength, AniPolkaVertCheckSum);


#endif


#endif //_AniPolkaVert_h_
