#ifndef _PostProcessVert_h_
#define _PostProcessVert_h_


// Header generated from binary by WriteAsBinHeader()..
static const int PostProcessVertLength = 69;
static const unsigned int PostProcessVert[PostProcessVertLength]={
    0x20205356,    0xFFFF0008,    0x00000048,    0x01020000,    0x00000003,    0x00000002,    0x00000000,    0x00000000,    0x00000002,    0x00000002,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000029,    0x00000000,    0x00000000,    0x00000000,
    0x00F800E4,    0x00000000,    0x00000000,    0x00010000,    0x00980154,    0x00000000,    0x00000000,    0x00000000,    0x1E000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x3F800000,    0x3F800000,    0x3F800000,    0x3F800000,    0x0000000C,    0x00000009,
    0x00000009,    0x00000000,    0x00000000,    0x00000016,    0x00000009,    0x00000003,    0x00000000,    0x00000004,    0x00000000,    0x0000000B,
    0x00000009,    0x00010004,    0x00000000,    0x00000020,    0x00000008,    0x00000003,    0x00010004,    0x00000004,    0x505F6C67,    0x7469736F,
    0x006E6F69,    0x74726576,    0x6F507865,    0x54690073,    0x6F437865,    0x0064726F,    0x43786574,    0x64726F6F,    0x00000000,};

//checksum generated by simpleCheckSum()
static const unsigned int PostProcessVertCheckSum = 249;

static const char* PostProcessVertText = 
    "\n"
    "attribute vec4 vertexPos;\n"
    "attribute vec2 iTexCoord;\n"
    "\n"
    "varying vec2 texCoord;\n"
    "\n"
    "void main()\n"
    "{\n"
    "        gl_Position = vertexPos;\n"
    "        texCoord = iTexCoord.xy;\n"
    "}";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader PostProcessVertShader(PostProcessVertText, PostProcessVert, PostProcessVertLength, PostProcessVertCheckSum);


#endif


#endif //_PostProcessVert_h_
