#ifndef _SampleVert_h_
#define _SampleVert_h_


// Header generated from binary by WriteAsBinHeader()..
static const int SampleVertLength = 144;
static const unsigned int SampleVert[SampleVertLength]={
    0x20205356,    0xFFFF0008,    0x00000048,    0x01020000,    0x0000000D,    0x0000000A,    0x00000000,    0x00000000,    0x00000001,    0x00000002,
    0x00000002,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000022,    0x00000000,    0x00000000,    0x02020000,
    0x237821E4,    0x00000000,    0x00E40101,    0x02035500,    0x2EF821E4,    0x00000000,    0x00E40101,    0x0204AA00,    0x2EF821E4,    0x00000000,
    0x00E40101,    0x0205FF00,    0x0EF821E4,    0x00000000,    0x00000000,    0x02060000,    0x237822E4,    0x00000000,    0x00E40102,    0x02075500,
    0x2EF822E4,    0x00000000,    0x00E40102,    0x0208AA00,    0x2EF822E4,    0x00000000,    0x00E40102,    0x0209FF00,    0x0EF822E4,    0x00000000,
    0x00000000,    0x01020000,    0x084020FF,    0x00000000,    0x00000000,    0x0102FF01,    0x033820A4,    0x00000000,    0x00000000,    0x01010000,
    0x00F800E4,    0x00000000,    0x00000000,    0x01000000,    0x00B801A4,    0x00000000,    0x00000000,    0x00000000,    0x1E000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x3F800000,    0x3F800000,    0x3F800000,    0x3F800000,    0x00000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,
    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,    0x00000000,
    0x0000000C,    0x00000009,    0x00000009,    0x00000000,    0x00000000,    0x00000000,    0x0000000B,    0x00000009,    0x00010004,    0x00000000,
    0x0000001D,    0x00000004,    0x00000006,    0x00010004,    0x00000004,    0x00000016,    0x00000002,    0x0000000E,    0x00020001,    0x00000018,
    0x00000019,    0x00000003,    0x0000000E,    0x00020001,    0x00000008,    0x505F6C67,    0x7469736F,    0x006E6F69,    0x74726576,    0x6F507865,
    0x766D0073,    0x70766D00,    0x6F506E00,    0x00000073,};

//checksum generated by simpleCheckSum()
static const unsigned int SampleVertCheckSum = 217;

static const char* SampleVertText = 
    "\n"
    "attribute vec4 vertexPos;\n"
    "attribute vec4 iNormal;\n"
    "\n"
    "uniform mat4 mv;\n"
    "uniform mat4 mvp;\n"
    "uniform mat4 normalMat;\n"
    "\n"
    "varying vec3 nPos;\n"
    "\n"
    "void main()\n"
    "{\n"
    "        gl_Position = mvp * vertexPos;\n"
    "        vec4 tmp = mv*vertexPos;\n"
    "        nPos = tmp.xyz/tmp.w;\n"
    "}\n"
    "\n"
    "";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader SampleVertShader(SampleVertText, SampleVert, SampleVertLength, SampleVertCheckSum);


#endif


#endif //_SampleVert_h_
