; Copyright (c) Samsung Electronics. Co. LTD.  All rights reserved.
;
; THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
; ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
; THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
; PARTICULAR PURPOSE.

; generated by ARM/Thumb C/C++ Compiler, RVCT2.2 [Build 616]
    
        AREA |.text|, CODE, READONLY, ALIGN=2

_fglSendToFIFO32 PROC ; r0 -> bytes, r1 -> buffer
        stmfd        sp!,{r2 - r6, lr}
;        LDR      r2,|L1.104| ; FIFO register   ; already set in r2 , JJG 

        CMP      r0,#0xc ; in case of three words
        BNE      |L1.47|
        LDMIA    r1!, {r3-r5}
        stmia    r2!, {r3-r5}
        ; Goto return
        MOV      r0,#1
        ldmfd        sp!, {r2 - r6, pc}
        ;bx            lr

|L1.47|        
        CMP      r0,#0x10 ; in case of four words
        BNE      |L1.48|
        LDMIA    r1!, {r3-r6}
        stmia    r2!, {r3-r6}
        ; Goto return
        MOV      r0,#1
        ldmfd        sp!, {r2 - r6, pc}
        ;bx            lr
    
|L1.48|                    
        CMP      r0,#0x8 ; in case of two words
        BNE      |L1.49|
        LDMIA    r1!, {r3-r4}
        stmia    r2!, {r3-r4}
        ; Goto return
        MOV      r0,#1
        ldmfd        sp!, {r2 - r6, pc}
        ;bx            lr
|L1.49|                    
        CMP      r0,#0x4 ; in case of one words
        BNE      |L1.100|
        LDR      r3,[r1]
        STR      r3,[r2]
        ; Goto return
        MOV      r0,#1
        ldmfd        sp!, {r2 - r6, pc}
        ;bx            lr

|L1.100|
        CMP      r0,#0x0 ; general cases
        BEQ      |L1.101|
        LDR      r3,[r1], #4 
        STR      r3,[r2], #4
        SUB      r0,r0,#4
        B        |L1.100|
|L1.101|
        MOV         r0,#1
        ldmfd        sp!, {r2 - r6, pc}
        ;bx            lr
    
;|L1.104|
;        DCD      0xB570C000
        
        ENDP

        EXPORT _fglSendToFIFO32

        
        END
