//
// Copyright (c) Hiteg Ltd.  All rights reserved.
//
//
/*++
THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.
Copyright (c) 2012. Hiteg Ltd  All rights reserved.

Module Name:  ExternalPowerControl

Abstract:

    WinCE driver to control external power modules found on the TenByTen6410

rev:
	2012.03.30	: initial version, by Sven Riemann sven.riemann@hiteg.com

Notes: 
	.dll has to be added in platform.bib
		EPCTL.dll  $(_FLATRELEASEDIR)\EPCTL.dll            NK  SHK

	EPCTL.REG file should be included into final .reg file ( this should happen automatically ...(M$)... please check)
--*/
#ifndef _EXTPWRCTL_H_
#define _EXTPWRCTL_H_


//
// ExtPwrCtl Bus Driver IOCTLS
//
#define FILE_DEVICE_EPCTL     FILE_DEVICE_CONTROLLER
#define EPCTL_FN_BASE		  2048


// IN:  PSPI_IO_DESC
#define IOCTL_LCD_ON_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_USB_ON_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CAMERA_ON_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DAC0_ON_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DAC1_ON_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ETH_ON_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WIFI_ON_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_LCD_OFF_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_USB_OFF_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+8, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CAMERA_OFF_SET	CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+9, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DAC0_OFF_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+10, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DAC1_OFF_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+11, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ETH_OFF_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+12, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WIFI_OFF_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+13, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ALL_OFF_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+14, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SLEEP_SET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+15, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ALL_ON_SET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+16, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_AWAKE_SET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+17, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_LCD_GET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+18, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_USB_GET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+19, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CAMERA_GET		CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+20, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DAC0_GET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+21, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DAC1_GET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+22, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ETH_GET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+23, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WIFI_GET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+24, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ALL_GET			CTL_CODE(FILE_DEVICE_EPCTL, EPCTL_FN_BASE+25, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif // _EXTPWRCTL_H_