//
// Copyright (c) Samsung Electronics. Co. LTD.  All rights reserved.
//
/*++
THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.

*/

#ifndef __SAMSUNG_SYSLSI_APDEV_MFC_PWR_MGMT_H__
#define __SAMSUNG_SYSLSI_APDEV_MFC_PWR_MGMT_H__


BOOL Mfc_Pwr_On();
BOOL Mfc_Pwr_Off();

BOOL Mfc_Clk_On();
BOOL Mfc_Clk_Off();

#endif /* __SAMSUNG_SYSLSI_APDEV_MFC_PWR_MGMT_H__ */
