//
// Copyright (c) Samsung Electronics. Co. LTD.  All rights reserved.
//
/*++
THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.

*/


#ifndef __SAMSUNG_SYSLSI_APDEV_MFC_SET_CLK_H__
#define __SAMSUNG_SYSLSI_APDEV_MFC_SET_CLK_H__


#define MFC_CLOCK_DIVIDER_RATIO_HALF    2

BOOL Mfc_Set_ClkDiv(int divider);


#endif /* __SAMSUNG_SYSLSI_APDEV_MFC_SET_CLK_H__ */
